import "dotenv/config";

export const {
  PORT,
  FE_URL,
  NODEMAILER_EMAIL,
  NODEMAILER_PASS,
  SECRET_KEY,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_CLOUD_NAME,
} = process.env;
